### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by adhjort**

### CODE REVIEW

**Review by lawrennd — COMMENTED** [review]
Hi Anders, Can you provide context to this pull request? What are the changes to the PDF and why?

**Comment by adhjort** [comment]
Hi Neil, 

Apologize for not providing context. I was emailing with Markus Kaiser about the issue last week and explained the situation to him, and I thought he was the only one managing this repo. 

There was an error in the original manuscript. The error relates to the results in the "Mondrian CQR" row in Table 1, which is updated in the new file I added. The original results were wrong due to a coding error on my part. I realized this pretty quickly after submitting the manuscript to the COPA conference and notified one of the editors, Khuong An Nguyen. He told me that I should make a pull request when the files were published on GitHub. I am happy to provide this email exchange if necessary. 

Let me know if you need any more details from me. 

Regards, 
Anders

**Comment by lawrennd** [comment]
All context should also be provided in github so we have a public record.



Neil
—
Professor Neil Lawrence
http://inverseprobability.com
________________________________

**Comment by adhjort** [comment]
Of course, I fully agree and understand. Apologize again. 

Do you need more documentation and context from me at the current time?

**Comment by mrksr** [comment]
Looks good, thanks Anders! :)

**Pull request merged**
